# Nivell 1

## Ejercicio 1  
Pseudocódigo:

-- Desarrollar las siguientes funciones:

obtener_datos
+ Requisitos : (Opcional) diccionario o lista de datos
+ Input de los campos pedidos uno a uno y guardarlos en un diccionario
+ Datos a obtener (diccionario):
+ - Nombre y Apellidos
+ - Teléfono de contacto
+ - Años de experiencia dentro de la empresa
+ - Conocimiento de Catalán (0-3 puntos)
0 = sin conocimiento
1 = hasta nivel B1
2 = nivel B2
3 = C1 o superior
+ - Dominio de Excel (0-3 puntos)
0 = nivel básico
1 = uso de funciones
2 = tablas dinámicas
3 = Visual Basic y Macros
+ - Título académico (0-3 puntos)
0 = ESO
1 = FP
2 = Universidad
3 = Máster o superior
+ Valida los datos usando la función validar_dades
+ Retorna : diccionario con los datos validados

validar_dades
+ Requisitos : variable dato y tipo de dato
+ Validar el dato pasado por parámetro según su tipo (segundo parámetro) y, en caso de dato no válido, obliga su rectificación con un máximo de tres intentos
+ Devuelve : valor validado o False

calcular_puntuacio
+ Requisitos : Recibe el diccionario del candidato con los datos introducidos y validados
+ Calcularemos la puntuación de la candidatura y la guardaremos en el mismo diccionario:
puntuacio_total = experiencia (años * 1.5) + catalán + excel + titulación
+ Retorna : Diccionario

classificar_candidat  
+ Requisitos : Recibe el diccionario del candidato con los datos introducidos y validados y su puntuación
+ A partir de la puntuacio_total guardada en el diccionario se calcula la 'clasificación' que también se guarda en el diccionario de la candidatura siguiendo este criterio:
+ clasificación = "Prioritat Alta" si la puntuacio_total es igual o mayor a 12
+ clasificación = "Candidat adequat" si la puntuacio_total es entre 8 y 11
+ clasificación = "No prioritari" si la puntuacio_total es menor a 8
+ Retorna : Diccionario

mostrar_individual
+ Requisitos : Recibe el diccionario del candidato con los datos introducidos y validados y su puntuación
+ Muestra (print) la información que ha introducido la persona candidata y su puntuación calculada ( no la clasificación )
+ Retorna : Nada

mostrar_informe
+ Requisitos : Recibe agrupación (set) de más de una candidatura (diccionarios) para poder ordenarlas y mostrarlas
+ Ordena la agrupación de mayor puntuación a menos de los diccionarios según los campos 'clasificación', y en caso de empate, con 'puntuación_total' más alta:
+ - Primero los de clasificación 'Prioritat Alta'
+ - Después los de clasificación 'Candidat adequat'
+ - Finalmente los de clasificación 'No prioritari'

main_seleccio # orquesta todas las funciones
+ Requisitos : (Opcional) lista o set de candidaturas
+ Mostraremos un mensaje de funcionamiento del proceso para información de la persona candidata
+ Definiremos la agrupación (set) donde se guardarán los diccionarios de las candidaturas
+ Crearemos un bucle de 10 iteraciones donde:
+ - Se preguntará si se quiere introducir una candidatura (si es así seguimos)
+ - Crearemos un diccionario (candidatura)
+ - Utilizaremos las funciones anteriores en este orden y con el diccionario creado:
+ - - obtenir_dades  -- Dentro llamará validar_dades a cada input
+ - - calcular_puntuacio  
+ - - classificar_candidat  
+ - - mostrar_individual  
+ - - Guardaremos el diccionario en el set
+ Una vez terminado el bucle, llamaremos la función mostrar_informe y finalizará la ejecución del programa.

+ + Gestión de errores: Permitiremos tres intentos por campo de cada candidatura, y se permitirá la salida del programa si faltan candidatos y no se quieren o pueden añadir.

### Función : validar_dades  
Recibe: variable dato y tipo de dato  
Acción : Validar el dato pasado por parámetro según su tipo (segundo parámetro) y, en caso de dato no válido, obliga su rectificación con un máximo de tres intentos  
Retorna : valor validado o False

In [ ]:
import re
import math

def validar_dades(dada, tipus):
  try:
    match tipus:
      case 'NomCognoms':
        if isinstance(dada, str) and len(dada.strip().split(' ')) >= 2:
          return dada.strip().capitalize()
      case 'Telefon':
        if re.match("^\\(?\\+?\\d{1,4}\\)?[-.\\s]?\\d{8,14}$",dada):
          return dada
      case 'AnysExp':
        if not isinstance(dada,int):
          dada = int(dada)
        if dada >= 0 and dada <= 70:
          return dada
      case 'Catala'|'Excel'|'Titol':
        if not isinstance(dada,int):
          dada = int(dada)
        if dada >= 0 and dada <= 3:
          return dada
      case _:
        return False
  except:
    return False
# test
print(validar_dades('7',"Catala"))

None

### Función : obtenir_dades  
Requisitos : none  
Acción :
Input de los campos, pedidos uno a uno, y guardarlos en un diccionario  
Datos a obtener:
+ Nom i Cognoms
+ Telèfon de contacte
+ Anys d'experiència dins de l'empresa
+ Coneixement de Català (0-3 punts)
+ - 0 = sense coneixement
+ - 1 = fins a nivell B1
+ - 2 = nivell B2
+ - 3 = C1 o superior
+ Domini d'Excel (0-3 punts)
+ - 0 = nivell bàsic
+ - 1 = ús de funcions
+ - 2 = taules dinàmiques
+ - 3 = Visual Basic i Macros
+ Títol acadèmic (0-3 punts)
+ - 0 = ESO
+ - 1 = FP
+ - 2 = Universitat
+ - 3 = Màster o superior  
Valida los datos usando la función : valida_dades  
Retorna : diccionario con los datos validados

In [ ]:
def obtenir_dades():
  candi = {
    "NomCognoms": "",
    "Telefon": "",
    "AnysExp": 0,
    "Catala": 0,
    "Excel": 0,
    "Titol": 0
  }
  candiMiss = {
    "NomCognoms": "Introdueix el teu nom i cognom/s\n",
    "Telefon": "Introdueix el teu telèfon de contacte (ex: +34 987654321)\n",
    "AnysExp": "Quants anys sencers fa que ets a l'empresa? (ex: 10)\n",
    "Catala": "Sel·lecciona el teu nivell de Coneixement de Català (ex: 2)\n0 = sense coneixement\n1 = fins a nivell B1\n2 = nivell B2\n3 = C1 o superior\n",
    "Excel": "Sel·lecciona el teu nivell de Excel (ex: 2)\n0 = nivell bàsic\n1 = ús de funcions\n2 = taules dinàmiques\n3 = Visual Basic i Macros\n",
    "Titol": "Sel·lecciona el teu Nivell Acadèmic (ex: 2)\n0 = ESO\n1 = FP\n2 = Universitat\n3 = Màster o superior\n"
  }
  ok = True
  for k in candi:
    i=0
    while i<3:
      val=validar_dades(input(candiMiss[k]),k)
      # print(val, k)
      if val is not None:
        candi[k] = val
        i=4
        ok = True
        continue
      else:
        if i<2:
          print("\nValor no vàlid, torna-ho a intentar\n")
        ok = False
        i+=1
    if not ok:
      print("\nNo podem inscriure't amb dades no vàlides.")
      break
  if ok:
    print("Gràcies per inscriure't\n")
  return candi
# test
obtenir_dades()

Introdueix el teu nom i cognom/s
sdfg sdgf
Introdueix el teu telèfon de contacte (ex: +34 987654321)
456

Valor no vàlid, torna-ho a intentar

Introdueix el teu telèfon de contacte (ex: +34 987654321)
987654321
Quants anys fa que ets a l'empresa? (ex: 10)
1
Sel·lecciona el teu nivell de Coneixement de Català (ex: 2)
0 = sense coneixement
1 = fins a nivell B1
2 = nivell B2
3 = C1 o superior
4

Valor no vàlid, torna-ho a intentar

Sel·lecciona el teu nivell de Coneixement de Català (ex: 2)
0 = sense coneixement
1 = fins a nivell B1
2 = nivell B2
3 = C1 o superior
4

Valor no vàlid, torna-ho a intentar

Sel·lecciona el teu nivell de Coneixement de Català (ex: 2)
0 = sense coneixement
1 = fins a nivell B1
2 = nivell B2
3 = C1 o superior
3
Sel·lecciona el teu nivell de Excel (ex: 2)
0 = nivell bàsic
1 = ús de funcions
2 = taules dinàmiques
3 = Visual Basic i Macros
34

Valor no vàlid, torna-ho a intentar

Sel·lecciona el teu nivell de Excel (ex: 2)
0 = nivell bàsic
1 = ús de funcions
2 = taules dinàmiques
3 = Visual Basic i Macros
4

Valor no vàlid, torna-ho a intentar

Sel·lecciona el teu nivell de Excel (ex: 2)
0 = nivell bàsic
1 = ús de funcions
2 = taules dinàmiques
3 = Visual Basic i Macros
3
Sel·lecciona el teu Nivell Acadèmic (ex: 2)
0 = ESO
1 = FP
2 = Universitat
3 = Màster o superior
3
Gràcies per inscriure't

{'NomCognoms': 'Sdfg sdgf',
 'Telefon': '987654321',
 'AnysExp': 1.0,
 'Catala': 3,
 'Excel': 3,
 'Titol': 3}

### Función: calcular_puntuacio  
Requisitos : Recibe el diccionario del candidato con los datos introducidos y validados  
Acción: Calcularemos la puntuación de la candidatura y la guardaremos en el mismo diccionario:  
puntuacio_total = experiencia (años * 1.5) + catalán + excel + titulación  
Retorna : Diccionario

In [ ]:
def calcular_puntuacio(candidat):
  candidat["puntuacio_total"] = float(candidat["AnysExp"]*1.5) + candidat["Catala"] + candidat["Excel"] + candidat["Titol"]
  return candidat

# test
calcular_puntuacio({'NomCognoms': 'Asd fd',
 'Telefon': '987654321',
 'AnysExp': 2.0,
 'Catala': 3,
 'Excel': 3,
 'Titol': 3})

{'NomCognoms': 'Asd fd',
 'Telefon': '987654321',
 'AnysExp': 2.0,
 'Catala': 3,
 'Excel': 3,
 'Titol': 3,
 'puntuacio_total': 12.0}

### Función : classificar_candidat  
Requisitos : Recibe el diccionario del candidato con los datos introducidos y validados y su puntuación  
Acción: A partir de la puntuacio_total guardada en el diccionario se calcula la 'classificacio' que también se guarda en el diccionario de la candidatura siguiendo este criterio:  
+ classificacio = "Prioritat Alta" si la puntuacio_total es igual o mayor a 12
+ classificacio = "Candidat adequat" si la puntuacio_total es entre 8 y 11
+ classificacio = "No prioritari" si la puntuacio_total es menor a 8  

Retorna : Diccionario

In [ ]:
def classificar_candidat(candidat):
  if candidat["puntuacio_total"] >= 12:
    candidat["classificacio"] = "Prioritat Alta"
  elif candidat["puntuacio_total"] >= 8:
    candidat["classificacio"] = "Candidat adequat"
  else:
    candidat["classificacio"] = "No prioritari"
  return candidat

# test
classificar_candidat({'NomCognoms': 'Asd fd',
 'Telefon': '987654321',
 'AnysExp': 2.0,
 'Catala': 3,
 'Excel': 3,
 'Titol': 3,
 'puntuacio_total': 7.0})

{'NomCognoms': 'Asd fd',
 'Telefon': '987654321',
 'AnysExp': 2.0,
 'Catala': 3,
 'Excel': 3,
 'Titol': 3,
 'puntuacio_total': 7.0,
 'classificacio': 'No prioritari'}

### Función : mostrar_individual  
Requisitos : Recibe el diccionario del candidato con los datos introducidos y validados y su puntuación  
Acción: Muestra (print) la información que ha introducido la persona candidata y su puntuación calculada ( no la clasificación )  
Retorna : Nada

In [ ]:
def mostrar_individual(candidat):
  print("\nCandidatura:")
  print(f"Nom i Cognoms: {candidat['NomCognoms']}")
  print(f"Telèfon de contacte: {candidat['Telefon']}")
  print(f"Anys d'experiència dins de l'empresa: {candidat['AnysExp']}")
  print(f"Coneixement de Català: {candidat['Catala']}")
  print(f"Domini d'Excel: {candidat['Excel']}")
  print(f"Títol acadèmic: {candidat['Titol']}")
  print(f"Puntuació total: {candidat['puntuacio_total']}\n")


# test
mostrar_individual({'NomCognoms': 'Asd fd',
 'Telefon': '987654321',
 'AnysExp': 2.0,
 'Catala': 3,
 'Excel': 3,
 'Titol': 3,
 'puntuacio_total': 12.0,
 'classificacio': 'Prioritat Alta'})

Candidatura:
Nom i Cognoms: Asd fd
Telèfon de contacte: 987654321
Anys d'experiència dins de l'empresa: 2.0
Coneixement de Català: 3
Domini d'Excel: 3
Títol acadèmic: 3
Puntuació total: 12.0

### Función : mostrar_informe  
Requisitos : Recibe agrupación de más de una candidatura (diccionarios) para poder mostrarlas ya ordenadas  
Acción : Ordena la agrupación de mayor puntuación a menos de los diccionarios según 'puntuación_total' más alta:  
+ Primero los de clasificación 'Prioritat Alta' - puntuación_total más alta
+ Después los de clasificación 'Candidat adequat' - siguiente
+ Finalmente los de clasificación 'No prioritari' - siguiente  
muestra por pantalla la información de cada candidatura

Retorna : Nada

In [ ]:
import pandas as pd

def mostrar_informe(candidats):
  dfcandidats = pd.DataFrame(candidats)
  display(dfcandidats.sort_values(by=['puntuacio_total'], ascending=[False]))

# test
diccandidats = [{'NomCognoms': 'Asd fd',
  'Telefon': '987654321',
  'AnysExp': 2.0,
  'Catala': 3,
  'Excel': 3,
  'Titol': 3,
  'puntuacio_total': 12.0,
  'classificacio': 'Prioritat Alta'},
 {'NomCognoms': 'Asd fd',
  'Telefon': '987654321',
  'AnysExp': 2.0,
  'Catala': 3,
  'Excel': 3,
  'Titol': 3,
  'puntuacio_total': 11.0,
  'classificacio': 'Prioritat Alta'}
]

mostrar_informe(diccandidats)

,NomCognoms,Telefon,AnysExp,Catala,Excel,Titol,puntuacio_total,classificacio
0,Asd fd,987654321,2.0,3,3,3,12.0,Prioritat Alta
1,Asd fd,987654321,2.0,3,3,3,11.0,Prioritat Alta

### Función : main_seleccio # orquesta todas las funciones  
Requisitos : (Opcional) lista de candidaturas  
Acción :
+ Mostraremos un mensaje de funcionamiento del proceso para información de la persona candidata  
+ Definiremos la agrupación donde se guardarán los diccionarios de las candidaturas  
+ Crearemos un bucle de 10 iteraciones donde:  
+ - Se preguntará si se quiere introducir una candidatura (si es así seguimos)
+ - Crearemos un diccionario (candidatura)
+ - Utilizaremos las funciones anteriores en este orden y con el diccionario creado:  
+ - obtenir_dades -- Dentro llamará validar_dades a cada input
+ - calcular_puntuacio
+ - classificar_candidat
+ - mostrar_individual
+ Guardaremos el diccionario
+ Una vez terminado el bucle, llamaremos la función mostrar_informe y finalizará la ejecución del programa.

+ Gestión de errores: Permitiremos tres intentos por campo de cada candidatura,
y se permitirá la salida del programa si faltan candidatos y no se quieren o pueden añadir.

In [ ]:
def main_seleccio(candidatures = None):
  if candidatures is None: # sin datos iniciales
    candidatures = []
    print("Aquest programa et permetrà intoduïr les dades de 10 candidatures i en farà calculs")
    while len(candidatures)<10:
      candidatures.append(obtenir_dades())
      seguir = input("Vols afegir una altra candidatura? Si/No")
      if seguir.lower() == "no":
        break
  else:  # con datos iniciales
    # creamos diccionario de candidaturas a partir del listado con las claves iniciales definidas
    # para cada candidato y el listado pasado por argumento con las candidaturas
    claves = ["NomCognoms", "Telefon", "AnysExp", "Catala", "Excel", "Titol"]
    liscandidats = []
    num_campos = len(claves)  # En este caso, 6
    for i in range(0, len(candidatures), num_campos):
        # Extraemos el bloque de 6 elementos para este candidato
        valores_candidato = candidatures[i : i + num_campos]
        # Combinamos las claves con este bloque de valores
        candidato_dict = dict(zip(claves, valores_candidato))
        # Lo añadimos a la lista final
        liscandidats.append(candidato_dict)
    for c in liscandidats:
      for k in c:
        if validar_dades(c[k], k) is None: # si hay datos no validos en un listado proporcionado se eliminará la candidatura del grupo
          print("\nDades no vàlides", k, c[k])
          print("\nS'ha eliminat la candidatura següent:")
          print(c)
          liscandidats.remove(c)
          break
    # acotamos a un máximo de 10 candidatos, para más optimización,
    # este acotamiento también se podría realizar después de los cálculos y con los datos ordenados por mayor puntuación
    if len(liscandidats) > 10:
      liscandidats = liscandidats[:10]
  # una vez tenemos la lista validada procedemos a hacer los calculos y displays
  for can in liscandidats:
    mostrar_individual(classificar_candidat(calcular_puntuacio(can)))
  # mostramos el informe final
  mostrar_informe(liscandidats)

In [ ]:
# Test y ejecución
inputs_test = [
    "Laura Serra", "608112233", 6, 3, 3, 3,
    "Clara Gómez", "655221199", 3, 3, 3, 2,
    "Sergio López", "644112211", 3, 2, 2, 2,
    "Candidat Error", "611000000", 5, 7, 3, 2, # Català = 7 → NO VÀLID
    "Marta Ruiz", "699887766", 2, 3, 2, 1,
    "Marc Vidal", "612443322", 6, 3, 3, 3,
    "Júlia Romero", "677998877", 5, 3, 3, 2,
    "Pol Navarro", "699554433", 4, 3, 2, 2,
    "David Ferrer", "677665544", 2, 1, 1, 1,
    "Anna Paredes", "633221144", 1, 2, 1, 0,
    "Anibal Paredes", "644272727", 1, 2, 1, 0,
    "Núria Casals", "600112200", 8, 2, 3, 3 # 11è candidat
]

# pruebas con el test proporcionado
main_seleccio(inputs_test)
# pruebas sin datos proporcionados, introducción manual, descomentar línea siguiente
# main_seleccio()

Dades no valides Catala 7
S'ha eliminat la candidatura següent:
{'NomCognoms': 'Candidat Error', 'Telefon': '611000000', 'AnysExp': 5, 'Catala': 7, 'Excel': 3, 'Titol': 2}

Candidatura:
Nom i Cognoms: Laura Serra
Telèfon de contacte: 608112233
Anys d'experiència dins de l'empresa: 6
Coneixement de Català: 3
Domini d'Excel: 3
Títol acadèmic: 3
Puntuació total: 18.0


Candidatura:
Nom i Cognoms: Clara Gómez
Telèfon de contacte: 655221199
Anys d'experiència dins de l'empresa: 3
Coneixement de Català: 3
Domini d'Excel: 3
Títol acadèmic: 2
Puntuació total: 12.5


Candidatura:
Nom i Cognoms: Sergio López
Telèfon de contacte: 644112211
Anys d'experiència dins de l'empresa: 3
Coneixement de Català: 2
Domini d'Excel: 2
Títol acadèmic: 2
Puntuació total: 10.5


Candidatura:
Nom i Cognoms: Marta Ruiz
Telèfon de contacte: 699887766
Anys d'experiència dins de l'empresa: 2
Coneixement de Català: 3
Domini d'Excel: 2
Títol acadèmic: 1
Puntuació total: 9.0


Candidatura:
Nom i Cognoms: Marc Vidal
Telèfon de contacte: 612443322
Anys d'experiència dins de l'empresa: 6
Coneixement de Català: 3
Domini d'Excel: 3
Títol acadèmic: 3
Puntuació total: 18.0


Candidatura:
Nom i Cognoms: Júlia Romero
Telèfon de contacte: 677998877
Anys d'experiència dins de l'empresa: 5
Coneixement de Català: 3
Domini d'Excel: 3
Títol acadèmic: 2
Puntuació total: 15.5


Candidatura:
Nom i Cognoms: Pol Navarro
Telèfon de contacte: 699554433
Anys d'experiència dins de l'empresa: 4
Coneixement de Català: 3
Domini d'Excel: 2
Títol acadèmic: 2
Puntuació total: 13.0


Candidatura:
Nom i Cognoms: David Ferrer
Telèfon de contacte: 677665544
Anys d'experiència dins de l'empresa: 2
Coneixement de Català: 1
Domini d'Excel: 1
Títol acadèmic: 1
Puntuació total: 6.0


Candidatura:
Nom i Cognoms: Anna Paredes
Telèfon de contacte: 633221144
Anys d'experiència dins de l'empresa: 1
Coneixement de Català: 2
Domini d'Excel: 1
Títol acadèmic: 0
Puntuació total: 4.5


Candidatura:
Nom i Cognoms: Anibal Paredes
Telèfon de contacte: 644272727
Anys d'experiència dins de l'empresa: 1
Coneixement de Català: 2
Domini d'Excel: 1
Títol acadèmic: 0
Puntuació total: 4.5

,NomCognoms,Telefon,AnysExp,Catala,Excel,Titol,puntuacio_total,classificacio
0,Laura Serra,608112233,6,3,3,3,18.0,Prioritat Alta
4,Marc Vidal,612443322,6,3,3,3,18.0,Prioritat Alta
5,Júlia Romero,677998877,5,3,3,2,15.5,Prioritat Alta
6,Pol Navarro,699554433,4,3,2,2,13.0,Prioritat Alta
1,Clara Gómez,655221199,3,3,3,2,12.5,Prioritat Alta
2,Sergio López,644112211,3,2,2,2,10.5,Candidat adequat
3,Marta Ruiz,699887766,2,3,2,1,9.0,Candidat adequat
7,David Ferrer,677665544,2,1,1,1,6.0,No prioritari
8,Anna Paredes,633221144,1,2,1,0,4.5,No prioritari
9,Anibal Paredes,644272727,1,2,1,0,4.5,No prioritari

## Ejercicio 2  
Pseudocódigo  

+ Función: processar_clients
+ - Args : diccionario de diccionarios de clientes (datos)
+ - Acción : calcula los factores pedidos y los guarda dentro del diccionario de cada cliente usando las funciones siguientes. (loop que recorre el diccionario principal y ejecuta las funciones por cada cliente)  
+ - Retorno : diccionario de diccionarios de clientes  

+ Función: obtenir_segment_i_factor: // segmento equivale al factor, ya que en sí és una segmentación, esto se calcula aquí y se usará en el main  
+ - Args: diccionari de 1 client
+ - Acción: calcula segmento y factor y añade los datos en el mismo diccionario del cliente  
 Códigos de comportamiento
0 → Navega però no afegeix productes
1 → Afegeix productes però no arriba al checkout
2 → Arriba al checkout però no paga
3 → Cistella de compra abandonat fa menys de 24 h
4 → Cistella de compra abandonat fa més de 24 h
+ - Retorno: diccionario del cliente con los nuevos campos y valores calculados  

+ Función: obtenir_factor_edat  
+ - Args: diccionario de 1 cliente
+ - Acción: calcula factor_edat y añade los datos en el mismo dicc  
 Factores según grupo de edad:
18-25 → 1.20
26-40 → 1.00
41-60 → 0.85
60+ → 0.70
+ - Retorno: diccionario del cliente con los nuevos campos y valores calculados  

+ Función: calcular_risc:  
+ - Args: diccionario de 1 cliente
+ - Acción: calcula riesgo y añade los datos en el mismo dicc  
 Fórmula del riesgo final
risc_final = factor codi * factor edat
+ - Retorno: diccionario del cliente con los nuevos campos y valores calculados  

+ Función: mostrar_dataframe  
+ - Args:  diccionario clientes   
+ - Acción: mostramos en formato tabla el diccionario de clientes convertido a dataframe (y sus datos):  
+ - Un DataFrame final con:
id_cliente
nombre
edad
grupo_edad
codigo_comportamiento
segment
missatge
factor_codi
factor_edat
risc_final
+ - Retorno: dataframe

+ Función: mostrar_respostes  
+ - Args:  dataframe clientes   
+ - Acción : calcular la mejor opción o segmento para cada pregunta  
+ - » 1. Quins clients s'han de contactar primer en una campanya de retargeting?  
+ - - Los que han añadido articulos al carrito pero no han terminado la compra.  

» 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents? (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?):
+ - - Mostramos los valores diferentes dentro de las mismas coincidencias de comportamiento  

» 3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?
+ - - Els de menor riesgo  

» 4. Quin client seria el més rendible de recuperar?
+ - - comportamiento de 1 a 3 y edadf de 26-60    

+ Función: main_marketing   
+ - Args : None
+ - Accion :
+ - definimos el diccionario de clientes propuesto  
+ - processar_clients  
+ - mostrar_dataframe  
+ - mostrar_respostes  
+ - Retorno: None

###  Función: obtenir_segment_i_factor:  
+ - Args: diccionari de 1 client y el dicc de factores
+ - Acción: calcula segmento y factor y añade los datos en el mismo diccionario del cliente  
 Códigos de comportamiento
0 → Navega però no afegeix productes
1 → Afegeix productes però no arriba al checkout
2 → Arriba al checkout però no paga
3 → Cistella de compra abandonat fa menys de 24 h
4 → Cistella de compra abandonat fa més de 24 h
+ - Retorno: diccionario del cliente con los nuevos campos y valores calculados

In [ ]:
def obtenir_segment_i_factor(client,factor_comportament):
  client["factor_codi"] = factor_comportament[client["codi_comportament"]]["factor"]
  client["segment"] = factor_comportament[client["codi_comportament"]]["segment"]
  client["missatge"] = factor_comportament[client["codi_comportament"]]["missatge"]
  return client

# test
factor_comportament = {
  0: {"factor":0.10,"segment":"Navega però no afegeix productes","missatge":"No trobes el que busques? Mira les nostres novetats!!"},
  1: {"factor":0.25,"segment":"Afegeix productes però no arriba al checkout","missatge":"Segur que no liproba? li encantaria!!"},
  2: {"factor":0.50,"segment":"Arriba al checkout però no paga","missatge":"Potser demà està més car!!"},
  3: {"factor":0.75,"segment":"Cistella de compra abandonada fa menys de 24 h","missatge":"Afanya't que s'estan esgotant!"},
  4: {"factor":0.90,"segment":"Cistella de compra abandonada fa més de 24 h","missatge":"Alguns productes ja s'han exhaurit, revisa la teva cistella i aprofita els descomptes!"}
}

obtenir_segment_i_factor({'id_client': 1, 'nom': 'Laura Serra', 'edat': 23, 'grup_edat': '18-25', 'codi_comportament': 4}, factor_comportament)

{'id_client': 1,
 'nom': 'Laura Serra',
 'edat': 23,
 'grup_edat': '18-25',
 'codi_comportament': 4,
 'factor_codi': 0.9,
 'segment': 'Cistella de compra abandonada fa més de 24 h',
 'missatge': "Alguns productes ja s'han exhaurit, revisa la teva cistella i aprofita els descomptes!"}

### Función: obtenir_factor_edat  
Args: diccionario de 1 cliente y dicc factores edad  
Acción: calcula factor_edat y añade los datos en el mismo dicc  
Factores según grupo de edad: 18-25 → 1.20 26-40 → 1.00 41-60 → 0.85 60+ → 0.70  
Retorno: diccionario del cliente con los nuevos campos y valores calculados

In [ ]:
def obtenir_factor_edat(client,fedat):
  client["factor_edat"] = fedat[client["grup_edat"]]
  return client

# test
fedat = {
  "18-25": 1.20,
  "26-40": 1.00,
  "41-60": 0.85,
  "60+": 0.70
}
obtenir_factor_edat({'id_client': 1, 'nom': 'Laura Serra', 'edat': 23, 'grup_edat': '18-25', 'codi_comportament': 4, 'factor_codi': 0.1, 'segment': 'Navega però no afegeix productes', 'missatge': 'No trobes el que busques? Mira les nostres novetats!!'}, fedat)

{'id_client': 1,
 'nom': 'Laura Serra',
 'edat': 23,
 'grup_edat': '18-25',
 'codi_comportament': 4,
 'factor_codi': 0.1,
 'segment': 'Navega però no afegeix productes',
 'missatge': 'No trobes el que busques? Mira les nostres novetats!!',
 'factor_edat': 1.2}

### Función: calcular_risc:  
Args: diccionario de 1 cliente  
Acción: calcula riesgo y añade los datos en el mismo dicc  
Fórmula del riesgo final risc_final = factor codi * factor edat  
Retorno: diccionario del cliente con los nuevos campos y valores calculados

In [ ]:
def calcular_risc(client):
  client["risc_final"] = round(client["factor_codi"] * client["factor_edat"], 2)
  return client

# test
calcular_risc({'id_client': 1, 'nom': 'Laura Serra', 'edat': 23, 'grup_edat': '18-25', 'codi_comportament': 4,  'factor_codi': 0.1, 'segment': 'Navega però no afegeix productes', 'missatge': 'No trobes el que busques? Mira les nostres novetats!!', 'factor_edat': 1.2})

{'id_client': 1,
 'nom': 'Laura Serra',
 'edat': 23,
 'grup_edat': '18-25',
 'codi_comportament': 4,
 'factor_codi': 0.1,
 'segment': 'Navega però no afegeix productes',
 'missatge': 'No trobes el que busques? Mira les nostres novetats!!',
 'factor_edat': 1.2,
 'risc_final': 0.12}

### Función: processar_clients  
Args : diccionario de diccionarios de clientes y factores  
Acción : calcula los factores pedidos y los guarda dentro del diccionario de cada cliente usando las funciones siguientes. (loop que recorre el diccionario principal y ejecuta las funciones por cada cliente)  
Retorno : diccionario de diccionarios de clientes y factores

In [ ]:
def processar_clients(dictmain):
  for client in dictmain["clients"]:
    obtenir_segment_i_factor(client, dictmain["factor_comportament"])
    obtenir_factor_edat(client, dictmain["factor_edat"])
    calcular_risc(client)

  return dictmain

# test
dictmain = {
    "factor_edat": {
        "18-25": 1.20,
        "26-40": 1.00,
        "41-60": 0.85,
        "60+": 0.70
    },
    "factor_comportament": {
        0: {"factor":0.10,"segment":"Navega però no afegeix productes","missatge":"No trobes el que busques? Mira les nostres novetats!!"},
        1: {"factor":0.25,"segment":"Afegeix productes però no arriba al checkout","missatge":"Segur que no liproba? li encantaria!!"},
        2: {"factor":0.50,"segment":"Arriba al checkout però no paga","missatge":"Potser demà està més car!!"},
        3: {"factor":0.75,"segment":"Cistella de compra abandonada fa menys de 24 h","missatge":"Afanya't que s'estan esgotant!"},
        4: {"factor":0.90,"segment":"Cistella de compra abandonada fa més de 24 h","missatge":"Alguns productes ja s'han exhaurit, revisa la teva cistella i aprofita els descomptes!"}
    },
    "clients": [
        {"id_client": 1, "nom": "Laura Serra", "edat": 23, "grup_edat": "18-25", "codi_comportament": 4},
        {"id_client": 2, "nom": "Marc Vidal", "edat": 35, "grup_edat": "26-40", "codi_comportament": 3},
        {"id_client": 3, "nom": "Ana López", "edat": 29, "grup_edat": "26-40", "codi_comportament": 2},
        {"id_client": 4, "nom": "Joan Riera", "edat": 19, "grup_edat": "18-25", "codi_comportament": 2},
        {"id_client": 5, "nom": "Mónica Pérez", "edat": 47, "grup_edat": "41-60", "codi_comportament": 4},
        {"id_client": 6, "nom": "Luis García", "edat": 52, "grup_edat": "41-60", "codi_comportament": 1},
        {"id_client": 7, "nom": "Pilar Sánchez", "edat": 61, "grup_edat": "60+", "codi_comportament": 3},
        {"id_client": 8, "nom": "Eva Martín", "edat": 38, "grup_edat": "26-40", "codi_comportament": 0},
        {"id_client": 9, "nom": "Diego Romero", "edat": 24, "grup_edat": "18-25", "codi_comportament": 1},
        {"id_client": 10, "nom": "Núria Costa", "edat": 33, "grup_edat": "26-40", "codi_comportament": 4}
    ]
}

processar_clients(dictmain)

{'factor_edat': {'18-25': 1.2, '26-40': 1.0, '41-60': 0.85, '60+': 0.7},
 'factor_comportament': {0: {'factor': 0.1,
   'segment': 'Navega però no afegeix productes',
   'missatge': 'No trobes el que busques? Mira les nostres novetats!!'},
  1: {'factor': 0.25,
   'segment': 'Afegeix productes però no arriba al checkout',
   'missatge': 'Segur que no liproba? li encantaria!!'},
  2: {'factor': 0.5,
   'segment': 'Arriba al checkout però no paga',
   'missatge': 'Potser demà està més car!!'},
  3: {'factor': 0.75,
   'segment': 'Cistella de compra abandonada fa menys de 24 h',
   'missatge': "Afanya't que s'estan esgotant!"},
  4: {'factor': 0.9,
   'segment': 'Cistella de compra abandonada fa més de 24 h',
   'missatge': "Alguns productes ja s'han exhaurit, revisa la teva cistella i aprofita els descomptes!"}},
 'clients': [{'id_client': 1,
   'nom': 'Laura Serra',
   'edat': 23,
   'grup_edat': '18-25',
   'codi_comportament': 4,
   'factor_codi': 0.9,
   'segment': 'Cistella de compra abandonada fa més de 24 h',
   'missatge': "Alguns productes ja s'han exhaurit, revisa la teva cistella i aprofita els descomptes!",
   'factor_edat': 1.2,
   'risc_final': 1.08},
  {'id_client': 2,
   'nom': 'Marc Vidal',
   'edat': 35,
   'grup_edat': '26-40',
   'codi_comportament': 3,
   'factor_codi': 0.75,
   'segment': 'Cistella de compra abandonada fa menys de 24 h',
   'missatge': "Afanya't que s'estan esgotant!",
   'factor_edat': 1.0,
   'risc_final': 0.75},
  {'id_client': 3,
   'nom': 'Ana López',
   'edat': 29,
   'grup_edat': '26-40',
   'codi_comportament': 2,
   'factor_codi': 0.5,
   'segment': 'Arriba al checkout però no paga',
   'missatge': 'Potser demà està més car!!',
   'factor_edat': 1.0,
   'risc_final': 0.5},
  {'id_client': 4,
   'nom': 'Joan Riera',
   'edat': 19,
   'grup_edat': '18-25',
   'codi_comportament': 2,
   'factor_codi': 0.5,
   'segment': 'Arriba al checkout però no paga',
   'missatge': 'Potser demà està més car!!',
   'factor_edat': 1.2,
   'risc_final': 0.6},
  {'id_client': 5,
   'nom': 'Mónica Pérez',
   'edat': 47,
   'grup_edat': '41-60',
   'codi_comportament': 4,
   'factor_codi': 0.9,
   'segment': 'Cistella de compra abandonada fa més de 24 h',
   'missatge': "Alguns productes ja s'han exhaurit, revisa la teva cistella i aprofita els descomptes!",
   'factor_edat': 0.85,
   'risc_final': 0.77},
  {'id_client': 6,
   'nom': 'Luis García',
   'edat': 52,
   'grup_edat': '41-60',
   'codi_comportament': 1,
   'factor_codi': 0.25,
   'segment': 'Afegeix productes però no arriba al checkout',
   'missatge': 'Segur que no liproba? li encantaria!!',
   'factor_edat': 0.85,
   'risc_final': 0.21},
  {'id_client': 7,
   'nom': 'Pilar Sánchez',
   'edat': 61,
   'grup_edat': '60+',
   'codi_comportament': 3,
   'factor_codi': 0.75,
   'segment': 'Cistella de compra abandonada fa menys de 24 h',
   'missatge': "Afanya't que s'estan esgotant!",
   'factor_edat': 0.7,
   'risc_final': 0.52},
  {'id_client': 8,
   'nom': 'Eva Martín',
   'edat': 38,
   'grup_edat': '26-40',
   'codi_comportament': 0,
   'factor_codi': 0.1,
   'segment': 'Navega però no afegeix productes',
   'missatge': 'No trobes el que busques? Mira les nostres novetats!!',
   'factor_edat': 1.0,
   'risc_final': 0.1},
  {'id_client': 9,
   'nom': 'Diego Romero',
   'edat': 24,
   'grup_edat': '18-25',
   'codi_comportament': 1,
   'factor_codi': 0.25,
   'segment': 'Afegeix productes però no arriba al checkout',
   'missatge': 'Segur que no liproba? li encantaria!!',
   'factor_edat': 1.2,
   'risc_final': 0.3},
  {'id_client': 10,
   'nom': 'Núria Costa',
   'edat': 33,
   'grup_edat': '26-40',
   'codi_comportament': 4,
   'factor_codi': 0.9,
   'segment': 'Cistella de compra abandonada fa més de 24 h',
   'missatge': "Alguns productes ja s'han exhaurit, revisa la teva cistella i aprofita els descomptes!",
   'factor_edat': 1.0,
   'risc_final': 0.9}]}

### Función: mostrar_dataframe  
Args: diccionario clientes  
Acción: mostramos en formato tabla el diccionario de clientes convertido a dataframe (y sus datos):  
Un DataFrame final con:   
id_cliente nombre edad grupo_edad codigo_comportamiento segment missatge factor_codi factor_edat risc_final  
Retorno: dataframe

In [ ]:
import pandas as pd
def mostrar_dataframe(clients):
  df = pd.DataFrame(clients)
  display(df)
  return df

# test
mostrar_dataframe(dictmain['clients'])

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final
0,1,Laura Serra,23,18-25,4,0.90,Cistella de compra abandonada fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.20,1.08
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonada fa menys de 24 h,Afanya't que s'estan esgotant!,1.00,0.75
2,3,Ana López,29,26-40,2,0.50,Arriba al checkout però no paga,Potser demà està més car!!,1.00,0.50
3,4,Joan Riera,19,18-25,2,0.50,Arriba al checkout però no paga,Potser demà està més car!!,1.20,0.60
4,5,Mónica Pérez,47,41-60,4,0.90,Cistella de compra abandonada fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",0.85,0.77
5,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,Segur que no liproba? li encantaria!!,0.85,0.21
6,7,Pilar Sánchez,61,60+,3,0.75,Cistella de compra abandonada fa menys de 24 h,Afanya't que s'estan esgotant!,0.70,0.52
7,8,Eva Martín,38,26-40,0,0.10,Navega però no afegeix productes,No trobes el que busques? Mira les nostres nov...,1.00,0.10
8,9,Diego Romero,24,18-25,1,0.25,Afegeix productes però no arriba al checkout,Segur que no liproba? li encantaria!!,1.20,0.30
9,10,Núria Costa,33,26-40,4,0.90,Cistella de compra abandonada fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.00,0.90

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final
0,1,Laura Serra,23,18-25,4,0.90,Cistella de compra abandonada fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.20,1.08
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonada fa menys de 24 h,Afanya't que s'estan esgotant!,1.00,0.75
2,3,Ana López,29,26-40,2,0.50,Arriba al checkout però no paga,Potser demà està més car!!,1.00,0.50
3,4,Joan Riera,19,18-25,2,0.50,Arriba al checkout però no paga,Potser demà està més car!!,1.20,0.60
4,5,Mónica Pérez,47,41-60,4,0.90,Cistella de compra abandonada fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",0.85,0.77
5,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,Segur que no liproba? li encantaria!!,0.85,0.21
6,7,Pilar Sánchez,61,60+,3,0.75,Cistella de compra abandonada fa menys de 24 h,Afanya't que s'estan esgotant!,0.70,0.52
7,8,Eva Martín,38,26-40,0,0.10,Navega però no afegeix productes,No trobes el que busques? Mira les nostres nov...,1.00,0.10
8,9,Diego Romero,24,18-25,1,0.25,Afegeix productes però no arriba al checkout,Segur que no liproba? li encantaria!!,1.20,0.30
9,10,Núria Costa,33,26-40,4,0.90,Cistella de compra abandonada fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.00,0.90

### Función: mostrar_respostes  
Args: dataframe clientes  
Acción : calcular la mejor opción o segmento para cada pregunta  

» 1. Quins clients s'han de contactar primer en una campanya de retargeting?  
» 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents? (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?):  
» 3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?  
» 4. Quin client seria el més rendible de recuperar?  

Retorno: None

In [ ]:
def mostrar_respostes(dfclientes):
  # display secuencial de las preguntas propuestas y las respuestas calculadas u observadas según criterio propio
  print("\n\n1. Quins clients s'han de contactar primer en una campanya de retargeting?")
  print("- S'ha establert la classificació en tres trams sobre el factor final de risc en Alt, mitja i baix,\n i es proposa contactar amb els clients de classificació de risc Alt")
   # aplicamos el siguiente criterio para clasificar el factor final de riesgo en Alt, Mitjà i baix:
   # si ffr és menor o igual a 29 = baix
   # si ffr és entre 30 i 60 = mitjà
   # si ffr és major o igual a 61 = alt

   # usamos el método cut(), que limitará por los límites establecidos según nuestro criterio de puntuación del riesgo final,
   # asignando una etiqueta a cada franja, y dependiendo de la franja de cada cliente recibirá la etiqueta pertinente
  limits = [0,0.29,0.60,2]
  labels = ["baix","mitja","alt"]
  dfclientes["class_risc"] = pd.cut(dfclientes["risc_final"],bins=limits,labels=labels)
  res1 = dfclientes[dfclientes["class_risc"] == "alt"]
  display(res1)

  print("\n\n2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents?\n(Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?):")
  print("- Tot i tenir el mateix comportament, hi ha una gran diferència en el factor de risc inversament proporcional a l'edat ")
  res2 = dfclientes.sort_values(by='codi_comportament')
  display(res2)

  print("\n\n3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?")
  print("- Els clients amb un factor de risc baix no presenten urgència d'acció:")
  res3 = dfclientes[dfclientes["class_risc"] == "baix"]
  display(res3)

  print("\n\n4. Quin client seria el més rendible de recuperar?")
  print("- Els clients més rendibles de recuperar són els que abandonen el procés de compra un cop afegits productes a la cistella,\n amb i sense checkout, i entre franges d'edat de 26 a 60, ja que es considera que tenen un\n procés de compra madurat i no tant impulsiu com la franja més jove ")
  res4 = dfclientes[(dfclientes["codi_comportament"] >= 1) & (dfclientes["codi_comportament"] <= 3) & (dfclientes["grup_edat"] == "26-40")]
  display(res4)

# test
dfclients = pd.DataFrame(dictmain['clients'])
mostrar_respostes(dfclients)

1. Quins clients s'han de contactar primer en una campanya de retargeting?
- S'ha establert la classificació en tres trams sobre el factor final de risc en Alt, mitja i baix,
 i es proposa contactar amb els clients de classificació de risc Alt

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
0,1,Laura Serra,23,18-25,4,0.90,Cistella de compra abandonada fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.20,1.08,alt
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonada fa menys de 24 h,Afanya't que s'estan esgotant!,1.00,0.75,alt
4,5,Mónica Pérez,47,41-60,4,0.90,Cistella de compra abandonada fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",0.85,0.77,alt
9,10,Núria Costa,33,26-40,4,0.90,Cistella de compra abandonada fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.00,0.90,alt

2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents?
(Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?):
- Tot i tenir el mateix comportament, hi ha una gran diferència en el factor de risc inversament proporcional a l'edat

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
7,8,Eva Martín,38,26-40,0,0.10,Navega però no afegeix productes,No trobes el que busques? Mira les nostres nov...,1.00,0.10,baix
5,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,Segur que no liproba? li encantaria!!,0.85,0.21,baix
8,9,Diego Romero,24,18-25,1,0.25,Afegeix productes però no arriba al checkout,Segur que no liproba? li encantaria!!,1.20,0.30,mitja
3,4,Joan Riera,19,18-25,2,0.50,Arriba al checkout però no paga,Potser demà està més car!!,1.20,0.60,mitja
2,3,Ana López,29,26-40,2,0.50,Arriba al checkout però no paga,Potser demà està més car!!,1.00,0.50,mitja
6,7,Pilar Sánchez,61,60+,3,0.75,Cistella de compra abandonada fa menys de 24 h,Afanya't que s'estan esgotant!,0.70,0.52,mitja
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonada fa menys de 24 h,Afanya't que s'estan esgotant!,1.00,0.75,alt
0,1,Laura Serra,23,18-25,4,0.90,Cistella de compra abandonada fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.20,1.08,alt
4,5,Mónica Pérez,47,41-60,4,0.90,Cistella de compra abandonada fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",0.85,0.77,alt
9,10,Núria Costa,33,26-40,4,0.90,Cistella de compra abandonada fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.00,0.90,alt

3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?
- Els clients amb un factor de risc baix no presenten urgència d'acció:

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
5,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,Segur que no liproba? li encantaria!!,0.85,0.21,baix
7,8,Eva Martín,38,26-40,0,0.10,Navega però no afegeix productes,No trobes el que busques? Mira les nostres nov...,1.00,0.10,baix

4. Quin client seria el més rendible de recuperar?
- Els clients més rendibles de recuperar són els que abandonen el procés de compra un cop afegits productes a la cistella,
 amb i sense checkout, i entre franges d'edat de 26 a 60, ja que es considera que tenen un
 procés de compra madurat i no tant impulsiu com la franja més jove

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonada fa menys de 24 h,Afanya't que s'estan esgotant!,1.0,0.75,alt
2,3,Ana López,29,26-40,2,0.50,Arriba al checkout però no paga,Potser demà està més car!!,1.0,0.50,mitja

### Función: main_marketing  
Args : None  
Acción : Creamos el diccionario de diccionarios y lista propuesto y llamamos a la función que lo van a procesar:
+ processar_clients  

Finalmente mostramos los datos y las respuestas:  
+ mostrar_dataframe  
+ mostrar_respostes  
Retorno: None

In [ ]:
import pandas as pd
clients = [
      {"id_client": 1, "nom": "Laura Serra", "edat": 23, "grup_edat": "18-25", "codi_comportament": 4},
      {"id_client": 2, "nom": "Marc Vidal", "edat": 35, "grup_edat": "26-40", "codi_comportament": 3},
      {"id_client": 3, "nom": "Ana López", "edat": 29, "grup_edat": "26-40", "codi_comportament": 2},
      {"id_client": 4, "nom": "Joan Riera", "edat": 19, "grup_edat": "18-25", "codi_comportament": 2},
      {"id_client": 5, "nom": "Mónica Pérez", "edat": 47, "grup_edat": "41-60", "codi_comportament": 4},
      {"id_client": 6, "nom": "Luis García", "edat": 52, "grup_edat": "41-60", "codi_comportament": 1},
      {"id_client": 7, "nom": "Pilar Sánchez", "edat": 61, "grup_edat": "60+", "codi_comportament": 3},
      {"id_client": 8, "nom": "Eva Martín", "edat": 38, "grup_edat": "26-40", "codi_comportament": 0},
      {"id_client": 9, "nom": "Diego Romero", "edat": 24, "grup_edat": "18-25", "codi_comportament": 1},
      {"id_client": 10, "nom": "Núria Costa", "edat": 33, "grup_edat": "26-40", "codi_comportament": 4}
]
factor_edat={
      "18-25": 1.20,
      "26-40": 1.00,
      "41-60": 0.85,
      "60+": 0.70
}
factor_comportament={
      0: {"factor":0.10,"segment":"Navega però no afegeix productes","missatge":"No trobes el que busques? Mira les nostres novetats!!"},
      1: {"factor":0.25,"segment":"Afegeix productes però no arriba al checkout","missatge":"Segur que no li regalaras? li encantaria!!"},
      2: {"factor":0.50,"segment":"Arriba al checkout però no paga","missatge":"Potser demà està més car!!"},
      3: {"factor":0.75,"segment":"Cistella de compra abandonat fa menys de 24 h","missatge":"Afanya't que s'estan esgotant!"},
      4: {"factor":0.90,"segment":"Cistella de compra abandonat fa més de 24 h","missatge":"Alguns productes ja s'han exhaurit, revisa la teva cistella i aprofita els descomptes!"}
}
def main_marketing():
  # diccionario de diccionarios y lista tomados de Global
  dictmain = {
      "factor_edat": factor_edat,
      "factor_comportament": factor_comportament,
      "clients":clients
  }
  processar_clients(dictmain)

  dfclientes = mostrar_dataframe(dictmain["clients"])
  mostrar_respostes(dfclientes)

# test
main_marketing(clients)

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final
0,1,Laura Serra,23,18-25,4,0.90,Cistella de compra abandonat fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.20,1.08
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonat fa menys de 24 h,Afanya't que s'estan esgotant!,1.00,0.75
2,3,Ana López,29,26-40,2,0.50,Arriba al checkout però no paga,Potser demà està més car!!,1.00,0.50
3,4,Joan Riera,19,18-25,2,0.50,Arriba al checkout però no paga,Potser demà està més car!!,1.20,0.60
4,5,Mónica Pérez,47,41-60,4,0.90,Cistella de compra abandonat fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",0.85,0.77
5,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,Segur que no li regalaras? li encantaria!!,0.85,0.21
6,7,Pilar Sánchez,61,60+,3,0.75,Cistella de compra abandonat fa menys de 24 h,Afanya't que s'estan esgotant!,0.70,0.52
7,8,Eva Martín,38,26-40,0,0.10,Navega però no afegeix productes,No trobes el que busques? Mira les nostres nov...,1.00,0.10
8,9,Diego Romero,24,18-25,1,0.25,Afegeix productes però no arriba al checkout,Segur que no li regalaras? li encantaria!!,1.20,0.30
9,10,Núria Costa,33,26-40,4,0.90,Cistella de compra abandonat fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.00,0.90

1. Quins clients s'han de contactar primer en una campanya de retargeting?
- S'ha establert la classificació en tres trams sobre el factor final de risc en Alt, mitja i baix,
 i es proposa contactar amb els clients de classificació de risc Alt

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
0,1,Laura Serra,23,18-25,4,0.90,Cistella de compra abandonat fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.20,1.08,alt
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonat fa menys de 24 h,Afanya't que s'estan esgotant!,1.00,0.75,alt
4,5,Mónica Pérez,47,41-60,4,0.90,Cistella de compra abandonat fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",0.85,0.77,alt
9,10,Núria Costa,33,26-40,4,0.90,Cistella de compra abandonat fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.00,0.90,alt

2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents?
(Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?):
- Tot i tenir el mateix comportament, hi ha una gran diferència en el factor de risc inversament proporcional a l'edat

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
7,8,Eva Martín,38,26-40,0,0.10,Navega però no afegeix productes,No trobes el que busques? Mira les nostres nov...,1.00,0.10,baix
5,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,Segur que no li regalaras? li encantaria!!,0.85,0.21,baix
8,9,Diego Romero,24,18-25,1,0.25,Afegeix productes però no arriba al checkout,Segur que no li regalaras? li encantaria!!,1.20,0.30,mitja
3,4,Joan Riera,19,18-25,2,0.50,Arriba al checkout però no paga,Potser demà està més car!!,1.20,0.60,mitja
2,3,Ana López,29,26-40,2,0.50,Arriba al checkout però no paga,Potser demà està més car!!,1.00,0.50,mitja
6,7,Pilar Sánchez,61,60+,3,0.75,Cistella de compra abandonat fa menys de 24 h,Afanya't que s'estan esgotant!,0.70,0.52,mitja
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonat fa menys de 24 h,Afanya't que s'estan esgotant!,1.00,0.75,alt
0,1,Laura Serra,23,18-25,4,0.90,Cistella de compra abandonat fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.20,1.08,alt
4,5,Mónica Pérez,47,41-60,4,0.90,Cistella de compra abandonat fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",0.85,0.77,alt
9,10,Núria Costa,33,26-40,4,0.90,Cistella de compra abandonat fa més de 24 h,"Alguns productes ja s'han exhaurit, revisa la ...",1.00,0.90,alt

3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?
- Els clients amb un factor de risc baix no presenten urgència d'acció:

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
5,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,Segur que no li regalaras? li encantaria!!,0.85,0.21,baix
7,8,Eva Martín,38,26-40,0,0.10,Navega però no afegeix productes,No trobes el que busques? Mira les nostres nov...,1.00,0.10,baix

4. Quin client seria el més rendible de recuperar?
- Els clients més rendibles de recuperar són els que abandonen el procés de compra un cop afegits productes a la cistella,
 amb i sense checkout, i entre franges d'edat de 26 a 60, ja que es considera que tenen un
 procés de compra madurat i no tant impulsiu com la franja més jove

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonat fa menys de 24 h,Afanya't que s'estan esgotant!,1.0,0.75,alt
2,3,Ana López,29,26-40,2,0.50,Arriba al checkout però no paga,Potser demà està més car!!,1.0,0.50,mitja

# Nivell 2

## Ejercicio 1

S7N2E1:  
Análisis / Pseudocódigo:  
+ Dado que se va a recibir datos en bruto sobre pacientes y sus síntomas, lo primero que debemos hacer es normalizar dichos datos, elegiremos hacerlo en un diccionario para facilitar las operaciones necesarias que definiremos a continuación
+ La estructura de cada cadena de paciente según el ejemplo dado es la siguiente:
+ - Ejemplo : "Maria|45|tos, Fiebre Alta, dolor_pecho"
+ - Codificación : "Nombre|Edad|Síntomas (separados por comas)"
+ Una vez tengamos el diccionario anterior, añadiremos la valoración dependiendo de los síntomas proporcionados con los valores por síntoma siguientes:
+ - nivells_risc = {
    "fiebre_alta": 3,
    "dificultad_respirar": 5,
    "dolor_pecho": 4,
    "tos": 1,
    "fatiga": 1,
    "dolor_cabeza": 1
}
+ Seguiremos con calcular el riesgo total
+ Ordenaremos por mayor riesgo total
+ Pasaremos el diccionario a Dataframe y mostraremos los pacientes ordenados por mayor riesgo a fin de obtener un listado con criterio de prioridad de acción médica / tratamiento

### Función : asignar_riesgo  
Argumentos : string  
Acción : Asignará un valor numérico según el criterio proporcionado a cada síntoma  
Retorno : int

In [ ]:
def asignar_riesgo(sintoma):
    nivells_risc = {
        "fiebre_alta": 3,
        "dificultad_respirar": 5,
        "dolor_pecho": 4,
        "tos": 1,
        "fatiga": 1,
        "dolor_cabeza": 1
        }
    return nivells_risc.get(sintoma, 0)

# test
sintoma = "tos"
riesgo = asignar_riesgo(sintoma)
print(riesgo)

1

### Función : normalizar_datos  
Argumentos : String  
Acción : Crearemos un diccionario e introduciremos los datos de la cadena normalizados, y usaremos la función asignar_riesgo para cada síntoma, guardando los síntomas en un diccionario dentro del diccionario del paciente  
Retorno : diccionario de paciente

In [ ]:
def normalizar_datos(paciente):
    datos_paciente = {}
    datos = paciente.split("|")
    datos_paciente["nombre"] = datos[0]
    datos_paciente["edad"] = int(datos[1])
    sintomas = datos[2].split(",")
    sintomas_normalizados = [sintoma.strip().lower() for sintoma in sintomas]
    datos_paciente["sintomas"] = {}
    for sintoma in sintomas_normalizados:
        datos_paciente["sintomas"][sintoma] = asignar_riesgo(sintoma)
    return datos_paciente

# test
paciente = "Maria|45|tos, Fiebre Alta, dolor_pecho"
datos_paciente = normalizar_datos(paciente)
print(datos_paciente)

{'nombre': 'Maria', 'edad': 45, 'sintomas': {'tos': 1, 'fiebre alta': 0, 'dolor_pecho': 4}}

### Función : riesgo_total  
Argumentos : diccionario de paciente  
Acción : Suma los valores numéricos de los síntomas del paciente y los guarda en su mismo diccionario  
Retorno : diccionario de paciente

In [ ]:
def riesgo_total(paciente):
    riesgo = 0
    for sintoma, valor in paciente["sintomas"].items():
        riesgo += valor
    paciente["riesgo_total"] = riesgo
    return paciente

# test
paciente = normalizar_datos(paciente)
riesgo_total(paciente)
print(paciente)

{'nombre': 'Maria', 'edad': 45, 'sintomas': {'tos': 1, 'fiebre alta': 0, 'dolor_pecho': 4}, 'riesgo_total': 5}

### Función : ordena_prioridad  
Argumentos : diccionario de pacientes  
Acción : pasa el diccionario a dataframe y lo ordena de mayor riesgo_total a menor  
Retorno : dataframe

In [ ]:
import pandas as pd
def ordena_prioridad(pacientes):
    df = pd.DataFrame(pacientes)
    df = df.sort_values(by="riesgo_total", ascending=False)
    return df

#test
pacientes = [
    "Maria|45|tos, Fiebre Alta, dolor_pecho",
    "Luis|33|dolor_cabeza,faTiga",
    "Sara|67|fiebre alta, dificultad RESPIRAR, tos",
    "Jordi|52|fatiga , tos",
    "Anna|29|fiebre alta,dolor_cabeza"
]
pacientes_normalizados = [normalizar_datos(paciente) for paciente in pacientes]
pacientes_con_riesgo = [riesgo_total(paciente) for paciente in pacientes_normalizados]
df = ordena_prioridad(pacientes_con_riesgo)
display(df)

,nombre,edad,sintomas,riesgo_total
0,Maria,45,"{'tos': 1, 'fiebre alta': 0, 'dolor_pecho': 4}",5
1,Luis,33,"{'dolor_cabeza': 1, 'fatiga': 1}",2
3,Jordi,52,"{'fatiga': 1, 'tos': 1}",2
2,Sara,67,"{'fiebre alta': 0, 'dificultad respirar': 0, '...",1
4,Anna,29,"{'fiebre alta': 0, 'dolor_cabeza': 1}",1

### Función : main_triaje  
Argumentos : Listado de pacientes  
Acción : Normaliza los datos de los pacientes, asignando valor numérico a sus síntomas, calcula su riesgo total y finalmente muestra una tabla con todos los datos, ordenados por el riesgo total calculado  
Retorno : None

In [ ]:
def main_triaje(pacientes):
    pacientes_normalizados = [normalizar_datos(paciente) for paciente in pacientes]
    pacientes_con_riesgo = [riesgo_total(paciente) for paciente in pacientes_normalizados]
    df = ordena_prioridad(pacientes_con_riesgo)
    pd.set_option('display.max_colwidth', None) # para que no recorte en la celda de síntomas
    display(df)

# test
pacientes = [
    "Maria|45|tos, Fiebre Alta, dolor_pecho",
    "Luis|33|dolor_cabeza,faTiga",
    "Sara|67|fiebre alta, dificultad RESPIRAR, tos",
    "Jordi|52|fatiga , tos",
    "Anna|29|fiebre alta,dolor_cabeza"
]
main_triaje(pacientes)

,nombre,edad,sintomas,riesgo_total
0,Maria,45,"{'tos': 1, 'fiebre alta': 0, 'dolor_pecho': 4}",5
1,Luis,33,"{'dolor_cabeza': 1, 'fatiga': 1}",2
3,Jordi,52,"{'fatiga': 1, 'tos': 1}",2
2,Sara,67,"{'fiebre alta': 0, 'dificultad respirar': 0, 'tos': 1}",1
4,Anna,29,"{'fiebre alta': 0, 'dolor_cabeza': 1}",1

## Ejercicio 2

S7N2E2:  
Análisis / Pseudocódigo:  
+ Seguros . Este programa va calcular el riesgo, el precio estimado de póliza y el riesgo de fraude de los clientes definidos o dados.  
+ Contamos con la siguiente lista de diccionarios de clientes:  
clients = [   
  {"nom": "Ana", "edat": 42, "codi": 0},   
  {"nom": "Carlos", "edat": 30, "codi": 2},   
  {"nom": "Isabel", "edat": 55, "codi": 3},   
  {"nom": "Jorge", "edat": 40, "codi": 1},   
  {"nom": "Marta", "edat": 28, "codi": 0}   
]  

+ Y con el diccionario de criterios para los cálculos:  
nivells_seguro = {  
 0: {"categoria": "Baix risc", "preu_base": 120, "fraude": 0.01},   
 1: {"categoria": "Risc mitjà", "preu_base": 200, "fraude": 0.05},   
 2: {"categoria": "Risc alt", "preu_base": 350, "fraude": 0.15},   
 3: {"categoria": "Risc crític", "preu_base": 500, "fraude": 0.30}   
}  

+ La fórmula siguiente nos indica el cálculo del precio final:  
preu_final = preu_base * (1 + edat/100)  

+ Fn calc_nivells_seguro: Añadiremos los campos siguientes a cada diccionario de cliente, una vez calculado su valor, basándonos en el campo 'codi' de cada cliente:
+ - categoria  
+ - preu_base  
+ - prob_frau  
+ - preu_final
  
+ fn ordenar_clients: pasará el listado de diccionarios de clientes a dataframe y los ordenará. Criterio:  
+ - prob_frau (desc)  
+ - preu_final  

+ fn main_seguros :  Función principal donde se usarán las funciones definidas previamente para conseguir los resultados deseados, su salida será:  
+ - El display de un dataframe con los datos de los clientes procesados:  
+ - - Nom
+ - - Edat
+ - - Categoria
+ - - Preu_base
+ - - Preu_final
+ - - Prob_frau  

+ Y un apartado que responderá las preguntas siguientes:  
+ - - Quin client té més probabilitat de frau <-- el cliente con el campo 'Prob_frau' más alto  
+ - - Quin té el preu final més alt <-- el cliente con el campo 'Preu_final' más alto   
+ - - Qui seria prioritari de revisar manualment <-- el cliente con el cálculo de 'Prob_frau' y 'Preu_final' más alto

### Función :  calc_nivells_seguro   
Args :   Lista diccionarios, diccionario criterios  
Acción :  Añadiremos los campos siguientes a cada diccionario de cliente, una vez calculado su valor, basándonos en el campo 'codi' de cada cliente:
+ categoria = nivells_seguro.categoria
+ preu_base = nivells_seguro.preu_base
+ prob_frau = nivells_seguro.fraude
+ preu_final = preu_base * (1 + edat/100)  

+ - Se extraerán los valores de los campos del diccionario de criterio recibido para hacer los cálculos:  
nivells_seguro = {
0: {"categoria": "Baix risc", "preu_base": 120, "fraude": 0.01},
1: {"categoria": "Risc mitjà", "preu_base": 200, "fraude": 0.05},
2: {"categoria": "Risc alt", "preu_base": 350, "fraude": 0.15},
3: {"categoria": "Risc crític", "preu_base": 500, "fraude": 0.30}
}

Retorna :  lista diccionarios

In [ ]:
def calc_nivells_seguro(clients, nivells_seguro):
    for client in clients:
        codi = client["codi"]
        client["categoria"] = nivells_seguro[codi]["categoria"]
        preu_base = nivells_seguro[codi]["preu_base"]
        client["preu_base"] = preu_base
        client["prob_frau"] = nivells_seguro[codi]["fraude"]
        preu_final = preu_base * (1 + client["edat"] / 100)
        client["preu_final"] = preu_final
    return clients

# test
clients = [
    {"nom": "Ana", "edat": 42, "codi": 0},
    {"nom": "Carlos", "edat": 30, "codi": 2},
    {"nom": "Isabel", "edat": 55, "codi": 3},
    {"nom": "Jorge", "edat": 40, "codi": 1},
    {"nom": "Marta", "edat": 28, "codi": 0}
  ]
nivells_seguro = {
    0: {"categoria": "Baix risc", "preu_base": 120, "fraude": 0.01},
    1: {"categoria": "Risc mitjà", "preu_base": 200, "fraude": 0.05},
    2: {"categoria": "Risc alt", "preu_base": 350, "fraude": 0.15},
    3: {"categoria": "Risc crític", "preu_base": 50, "fraude": 0.30}
  }
calc_nivells_seguro(clients, nivells_seguro)
display(clients)

[{'nom': 'Ana',
  'edat': 42,
  'codi': 0,
  'categoria': 'Baix risc',
  'preu_base': 120,
  'prob_frau': 0.01,
  'preu_final': 170.39999999999998},
 {'nom': 'Carlos',
  'edat': 30,
  'codi': 2,
  'categoria': 'Risc alt',
  'preu_base': 350,
  'prob_frau': 0.15,
  'preu_final': 455.0},
 {'nom': 'Isabel',
  'edat': 55,
  'codi': 3,
  'categoria': 'Risc crític',
  'preu_base': 50,
  'prob_frau': 0.3,
  'preu_final': 77.5},
 {'nom': 'Jorge',
  'edat': 40,
  'codi': 1,
  'categoria': 'Risc mitjà',
  'preu_base': 200,
  'prob_frau': 0.05,
  'preu_final': 280.0},
 {'nom': 'Marta',
  'edat': 28,
  'codi': 0,
  'categoria': 'Baix risc',
  'preu_base': 120,
  'prob_frau': 0.01,
  'preu_final': 153.6}]

### Función :  ordenar_clients  
Args :   lista diccionarios clientes  
Acción :  pasará el listado de diccionarios de clientes a dataframe,  
los ordenará por 'prob_frau' (desc) y 'preu_final'  
y los mostrará.  
Retorna :  dataframe

In [ ]:
import pandas as pd
def ordenar_clients(clients):
    df = pd.DataFrame(clients)
    df = df.sort_values(by=["prob_frau", "preu_final"], ascending=[False, False])
    display(df)
    return df
# test
dfclients = ordenar_clients(clients)

      nom  edat  codi    categoria  preu_base  prob_frau  preu_final
2  Isabel    55     3  Risc crític         50       0.30        77.5
1  Carlos    30     2     Risc alt        350       0.15       455.0
3   Jorge    40     1   Risc mitjà        200       0.05       280.0
0     Ana    42     0    Baix risc        120       0.01       170.4
4   Marta    28     0    Baix risc        120       0.01       153.6

### Función : responde_preguntas  
Args :   dataframe  
Acción :  Da respuesta a las siguientes preguntas según criterio del programador :  
+ - - Quin client té més probabilitat de frau <-- el cliente con el campo 'Prob_frau' más alto  
+ - - Quin té el preu final més alt <-- el cliente con el campo 'Preu_final' más alto   
+ - - Qui seria prioritari de revisar manualment <-- el cliente con el cálculo de 'Prob_frau' y 'Preu_final' más alto   

Muestra las preguntas y resultados

Retorna :  dataframe

In [ ]:
def responde_preguntas(clients):
    # mostramos la 1a pregunta:
    print("\nQuin client té més probabilitat de frau ?")
    # respuesta
    display(clients.sort_values(by='prob_frau', ascending=False).head(1))
    # mostramos la 2a pregunta:
    print("\nQuin té el preu final més alt ?")
    # respuesta
    display(clients.sort_values(by="preu_final", ascending = False).head(1))
    # mostramos la 3a pregunta:
    print("\nQui seria prioritari de revisar manualment ?")
    # respuesta
    display(clients.sort_values(by=['prob_frau', 'preu_final'], ascending=[False, False]).head(1))
    print("Observamos que el cliente con más edad y mayor probabilidad de fraude tiene, no obstante, el precio final más bajo.\nEsto debe ser revisado!")
    return clients

# test
dfclients = responde_preguntas(dfclients)

Quin client té més probabilitat de frau ?

      nom  edat  codi    categoria  preu_base  prob_frau  preu_final
2  Isabel    55     3  Risc crític         50        0.3        77.5

Quin té el preu final més alt ?

      nom  edat  codi categoria  preu_base  prob_frau  preu_final
1  Carlos    30     2  Risc alt        350       0.15       455.0

Qui seria prioritari de revisar manualment ?

      nom  edat  codi    categoria  preu_base  prob_frau  preu_final
2  Isabel    55     3  Risc crític         50        0.3        77.5

Observamos que el cliente con más edad y mayor probabilidad de fraude tiene, no obstante, el precio final más bajo.
Esto debe ser revisado!

### Función : main_seguros   
Args : None  
Acción :  Función principal donde se usarán las funciones definidas previamente para conseguir los resultados deseados, su salida será:  
+ - El display de un dataframe con los datos de los clientes procesados:  
+ - - Nom
+ - - Edat
+ - - Categoria
+ - - Preu_base
+ - - Preu_final
+ - - Prob_frau  
+ - Muestra las preguntas y sus respuestas  

Retorna :  None

In [ ]:
def main_seguros():
  clients = [
    {"nom": "Ana", "edat": 42, "codi": 0},
    {"nom": "Carlos", "edat": 30, "codi": 2},
    {"nom": "Isabel", "edat": 55, "codi": 3},
    {"nom": "Jorge", "edat": 40, "codi": 1},
    {"nom": "Marta", "edat": 28, "codi": 0}
  ]
  nivells_seguro = {
    0: {"categoria": "Baix risc", "preu_base": 120, "fraude": 0.01},
    1: {"categoria": "Risc mitjà", "preu_base": 200, "fraude": 0.05},
    2: {"categoria": "Risc alt", "preu_base": 350, "fraude": 0.15},
    3: {"categoria": "Risc crític", "preu_base": 50, "fraude": 0.30}
  }
  calc_nivells_seguro(clients, nivells_seguro)
  # Ordena y muestra todos los clientes con los cálculos hechos y añadidos,
  # ordenados por el valor de probabilidad de fraude descendiente
  dfclients = ordenar_clients(clients)
  responde_preguntas(dfclients)

# test
main_seguros()

      nom  edat  codi    categoria  preu_base  prob_frau  preu_final
2  Isabel    55     3  Risc crític         50       0.30        77.5
1  Carlos    30     2     Risc alt        350       0.15       455.0
3   Jorge    40     1   Risc mitjà        200       0.05       280.0
0     Ana    42     0    Baix risc        120       0.01       170.4
4   Marta    28     0    Baix risc        120       0.01       153.6

Quin client té més probabilitat de frau ?

      nom  edat  codi    categoria  preu_base  prob_frau  preu_final
2  Isabel    55     3  Risc crític         50        0.3        77.5

Quin té el preu final més alt ?

      nom  edat  codi categoria  preu_base  prob_frau  preu_final
1  Carlos    30     2  Risc alt        350       0.15       455.0

Qui seria prioritari de revisar manualment ?

      nom  edat  codi    categoria  preu_base  prob_frau  preu_final
2  Isabel    55     3  Risc crític         50        0.3        77.5

Observamos que el cliente con más edad y mayor probabilidad de fraude tiene, no obstante, el precio final más bajo.
Esto debe ser revisado!

# Nivell 3

## Ejercicio 1

S7N3E1  
Pseudiocódigo :  

Crear una función principal y todas las subfunciones necesarias para:  

+ Función generar_contrasenya. Generar contraseñas de longitud variable.
+ - Aceptará por parámetro las siguientes variables:  
+ - - Longitud
+ - - Mayúsculas  
+ - - Minúsculas  
+ - - Números  
+ - - Signos especiales  
+ - Creará, a partir de los argumentos, una lista de carácteres que incuirán todas las opciones indicadas, para aplicar un random sobre la lista para extraer carácteres. Aleatorizar completamente la contraseña.  
+ - Retorna la contraseña generada

+ Función valida_contrasenya. Asegurar que como mínimo aparece un caracter de cada tipos seleccionado.   
+ - Aceptará por parámetro las siguientes variables:  
+ - - Contraseña a validar
+ - - Longitud
+ - - Mayúsculas  
+ - - Minúsculas  
+ - - Números  
+ - - Signos especiales  
+ - Creará expresión regular dependiendo de los parámetros recibidos y validará la contraseña recibida con dicha expresión regular.
+ - Se crea esta función aparte por si se decide en un futuro hacer sólo la validación de contraseñas generadas manualmente.
+ - Retorna True (si la validación es exitosa) o False

+ Función principal crear_contrasenya  
+ - Aceptará por parámetro las siguientes variables:  
+ - - Longitud
+ - - Mayúsculas  
+ - - Minúsculas  
+ - - Números  
+ - - Signos especiales  
+ Llamará a las funciones anteriores para generar una contraseña que cumpla con los argumentos pasados y validarla.
+ Retorna String, la contraseña generada y validada.

### Función :  generar_contrasenya  
Args : (Opcionales) longi int, may bool, min bool, num bool, sign bool  
Acción :  Genera una contraseña aleatoria con la longitud dada por param.,  
   conteniendo, o no, características alfanuméricas dadas por los demás   parámetros.  
   Si no se especifican argumentos se creará una contraseña segura estandar de 16 caracteres (todos True)
Retorno :  string

In [ ]:
import numpy as np
import string

# incializamos el generador de random
rng = np.random.default_rng()

def generar_contrasenya(longi = 16, may = True, min = True, num = True, sign = True):
  # generamos una pool de caracteres, numeros y signos
  pool = ''
  if may:
    pool += string.ascii_uppercase
  if min:
    pool += string.ascii_lowercase
  if num:
    pool += string.digits
  if sign:
    pool += string.punctuation

  # convertimos la pool en un array
  poolar = np.array(list(pool))

  # Usamos numpy para seleccionar los caracteres aleatoriamente
  selec = rng.choice(poolar, size=longi, replace=True)

  return "".join(selec)

# test
#generar_contrasenya(10, True, True, True, False)
generar_contrasenya()

'P[u3r(rXt<3vK9fH'

### Función :  valida_contraseña  
Args :   pwd string, (Opcionales) : longitud int, may bool, min bool, num bool, sign bool  
Acción :  genera expresión regular según los argumentos recibidos y valida que la contraseña pwd cumpla con los criterios de los demás argumentos.  
Si no se especifican los argumentos opcionales, se verificará como unaa contraseña segura estandar de 16 caracteres (todos True)
Retorno :  bool. True si es correcta, False si no lo es

In [ ]:
import re

def valida_contraseña(pwd: str, longi = 16, may = True, min = True, num = True, sign = True):
  # Construimos la cadena de validación
  reg = '^'
  if may:
    reg += '(?=.*[A-Z])'
  if min:
    reg += '(?=.*[a-z])'
  if num:
    reg += '(?=.*[0-9])'
  if sign:
    reg += '(?=.*[^A-Za-z0-9])'

  # Construcción limpia del cuerpo de caracteres permitidos
  cuerpo = ''
  if may:
    cuerpo += 'A-Z'
  if min:
    cuerpo += 'a-z'
  if num:
    cuerpo += '0-9'
  if sign:
    # string.punctuation contiene: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
    # Escapamos los caracteres conflictivos para que Regex no se confunda
    simbolos = re.escape(string.punctuation)
    cuerpo += simbolos

  # Cerramos el patrón con la longitud exacta
  reg += '[' + cuerpo + ']{' + str(longi) + '}$'

  # retornamos la validación
  return bool(re.match(reg, pwd))

# test
valida_contraseña('asdf123$.', 9, False, True, True, True)

True

### Función :  crear_contrasenya  
Args :  longitud int, may bool, min bool, num bool, sign bool  
Acción :  generará contraseñas aleatorias siguiendo los argumentos de indicaciones, y validará dichas contraseñas, una a una hasta que la contraseña generada sea validada correctamente  
Retorno :  string contraseña generada aleatoriamente y validada

In [ ]:
def crear_contrasenya(longitud = 16, may = True, min = True, num = True, sign = True):
  contrasenya = generar_contrasenya(longitud, may, min, num, sign)
  while not valida_contraseña(contrasenya, longitud, may, min, num, sign):
    contrasenya = generar_contrasenya(longitud, may, min, num, sign)
  return contrasenya

# test
crear_contrasenya(10, 1, True, 15, 98)

'zbv*0x1oG^'

## Ejercicio 2

Exercici 2: Processament automàtic de dades esportives
Ara formes part d'un equip d'analítica dins una organització esportiva que gestiona dades de la lliga catalana. La teva companya de feina vol automatitzar la lectura del seu arxiu històric de resultats i extreure les estadístiques més importants. T'ha demanat fer un petit sistema en Python que processi el fitxer 📄 "historic partits.txt"
🎯 Objectius
Mitjançant un codi modular, clar i documentat, el teu programa ha de calcular:

» 1.Quin equip és el més golejador.

» 2.Quin és el més golejat.

» 3.El nombre total de gols que ha fet cada equip.

» 4.La classificació final ordenada per punts on cada victòria suma 3 pts, cada empat 1 pts y cada derrota 0 pts.

En aquest nivell no es dona cap funció. Ets tu qui ha de dissenyar un flux complet. El codi ha de reflectir una bona organització interna.

### Función :  llegir_i_netejar_dades  
Args :  String. Ruta al fichero de texto (.txt) de los partidos  
Acción :  Abre el fichero pasado por argumento, lo lee a través de pandas indicando el separador, el nombre de las columnas y el motor (para evitar errores), y guarda en un dataframe.   
Estructura de línea original (.txt) : "Manlleu	0-1	Granollers"
+ Equipo local, goles local, Equipo visitante, goles visitante  
* Separación por tabulación '\t'  

Retorno :  dataframe de partidos

In [ ]:
import pandas as pd

def llegir_i_netejar_dades(docu):
  try:
    partits = {}
    # Leemos el fichero en formato columnas respetando los espacios complejos
    dfPartits = pd.read_csv(docu, sep=r'\t+|\s{2,}', header=None, names=['Local', 'Resultat', 'Visitant'], engine='python')
    dfPartits['Gols Local'] = dfPartits['Resultat'].str.split('-').str[0].astype(int)
    dfPartits['Gols Visitant'] = dfPartits['Resultat'].str.split('-').str[1].astype(int)
    dfPartits = dfPartits.drop('Resultat', axis=1)
  except FileNotFoundError as e:
    print(e)
    return None
  return dfPartits

# test
partits = llegir_i_netejar_dades('/content/drive/MyDrive/CURS ESP DATA/S7Data/historic partits.txt')
if partits is not None:
    print("Dades carregades correctament!")
    display(partits.head())

Dades carregades correctament!

        Local    Visitant  Gols Local  Gols Visitant
0     Manlleu  Granollers           0              1
1  Vilafranca    Terrassa           4              5
2        Olot  Granollers           5              0
3  Vilafranca     Manlleu           5              5
4    Cornellà        Prat           5              1

### Función :  calcular_estadistiques  
Args :  dataframe de partidos  
Acción :  extrae los datos necesarios del df y calcula por cada equipo:   
+ - el sumatorio de goles marcados  
+ - el sumatorio de goles recibidos
+ - los puntos ( siguiendo el criterio dado de "victoria + 3, empate +1, derrota +0"  
+ Guarda los datos en un diccionario de equipos  

Retorno : diccionario

In [ ]:
def calcular_estadistiques(partits):
  comptadors_equips = {}
  for index, row in partits.iterrows():
    local = row['Local']
    visitant = row['Visitant']
    gols_local = row['Gols Local']
    gols_visitant = row['Gols Visitant']
    if local not in comptadors_equips:
      comptadors_equips[local] = {'gols_favor': 0, 'gols_contra': 0, 'guanyats': 0, 'empatats': 0, 'perduts': 0, 'punts': 0}
    if visitant not in comptadors_equips:
      comptadors_equips[visitant] = {'gols_favor': 0, 'gols_contra': 0, 'guanyats': 0, 'empatats': 0, 'perduts': 0, 'punts': 0}

    # Acumulamos los goles marcados y recibidos de forma cruzada
    comptadors_equips[local]['gols_favor'] += gols_local
    comptadors_equips[local]['gols_contra'] += gols_visitant

    comptadors_equips[visitant]['gols_favor'] += gols_visitant
    comptadors_equips[visitant]['gols_contra'] += gols_local

    # Apliquem la lògica de punts de la lliga
    if gols_local > gols_visitant: # equipo local gana
      comptadors_equips[local]['guanyats'] += 1
      comptadors_equips[local]['punts'] += 3
      comptadors_equips[visitant]['perduts'] += 1
    elif gols_visitant > gols_local: # equipo local pierde
      comptadors_equips[local]['perduts'] += 1
      comptadors_equips[visitant]['punts'] += 3
      comptadors_equips[visitant]['guanyats'] += 1
    else: # empate
      comptadors_equips[local]['empatats'] += 1
      comptadors_equips[visitant]['empatats'] += 1
      comptadors_equips[local]['punts'] += 1
      comptadors_equips[visitant]['punts'] += 1

  return comptadors_equips

# test
comptadors_equips = calcular_estadistiques(partits)
display(comptadors_equips)

{'Manlleu': {'gols_favor': 106,
  'gols_contra': 118,
  'guanyats': 16,
  'empatats': 9,
  'perduts': 18,
  'punts': 57},
 'Granollers': {'gols_favor': 122,
  'gols_contra': 117,
  'guanyats': 21,
  'empatats': 4,
  'perduts': 24,
  'punts': 67},
 'Vilafranca': {'gols_favor': 157,
  'gols_contra': 172,
  'guanyats': 20,
  'empatats': 12,
  'perduts': 25,
  'punts': 72},
 'Terrassa': {'gols_favor': 147,
  'gols_contra': 164,
  'guanyats': 20,
  'empatats': 14,
  'perduts': 23,
  'punts': 74},
 'Olot': {'gols_favor': 132,
  'gols_contra': 144,
  'guanyats': 18,
  'empatats': 10,
  'perduts': 26,
  'punts': 64},
 'Cornellà': {'gols_favor': 147,
  'gols_contra': 146,
  'guanyats': 25,
  'empatats': 7,
  'perduts': 22,
  'punts': 82},
 'Prat': {'gols_favor': 106,
  'gols_contra': 111,
  'guanyats': 16,
  'empatats': 8,
  'perduts': 21,
  'punts': 56},
 'Cerdanyola': {'gols_favor': 117,
  'gols_contra': 133,
  'guanyats': 17,
  'empatats': 5,
  'perduts': 28,
  'punts': 56},
 'Sant Andreu': {'gols_favor': 123,
  'gols_contra': 134,
  'guanyats': 17,
  'empatats': 11,
  'perduts': 25,
  'punts': 62},
 'FC Barcelona': {'gols_favor': 125,
  'gols_contra': 115,
  'guanyats': 22,
  'empatats': 7,
  'perduts': 15,
  'punts': 73},
 'Badalona': {'gols_favor': 134,
  'gols_contra': 124,
  'guanyats': 18,
  'empatats': 14,
  'perduts': 16,
  'punts': 68},
 'Sabadell': {'gols_favor': 141,
  'gols_contra': 121,
  'guanyats': 26,
  'empatats': 7,
  'perduts': 15,
  'punts': 85},
 'Europa': {'gols_favor': 93,
  'gols_contra': 93,
  'guanyats': 12,
  'empatats': 5,
  'perduts': 16,
  'punts': 41},
 'Llagostera': {'gols_favor': 159,
  'gols_contra': 142,
  'guanyats': 29,
  'empatats': 7,
  'perduts': 20,
  'punts': 94},
 'Figueres': {'gols_favor': 161,
  'gols_contra': 154,
  'guanyats': 23,
  'empatats': 10,
  'perduts': 23,
  'punts': 79},
 'RCD Espanyol': {'gols_favor': 131,
  'gols_contra': 144,
  'guanyats': 23,
  'empatats': 11,
  'perduts': 21,
  'punts': 80},
 'Reus Deportiu': {'gols_favor': 119,
  'gols_contra': 111,
  'guanyats': 20,
  'empatats': 8,
  'perduts': 16,
  'punts': 68},
 'Nàstic de Tarragona': {'gols_favor': 130,
  'gols_contra': 148,
  'guanyats': 20,
  'empatats': 8,
  'perduts': 27,
  'punts': 68},
 'Lleida Esportiu': {'gols_favor': 129,
  'gols_contra': 133,
  'guanyats': 23,
  'empatats': 6,
  'perduts': 23,
  'punts': 75},
 'Girona FC': {'gols_favor': 139,
  'gols_contra': 94,
  'guanyats': 31,
  'empatats': 3,
  'perduts': 13,
  'punts': 96}}

### Función :  generar_informe_final  
Args :  diccionario
Acción :  Convierte el diccionario en dataframe y respondemos a las preguntas planteadas:    
+ - Cuál es el equipo que ha marcado más goles?
+ - Cuál es el equipo que ha marcado menos goles?
+ - Número total de goles que ha marcado cada equipo  
+ - Tabla clasificatoria, equipos ordenados por puntos de mayor a menor.   
+ Muestra las preguntas y los resultados de cada una, con el informe final siendo la tabla clasificatoria  

Retorno :  None

In [ ]:
def generar_informe_final(comptadors_equips):
  df_est = pd.DataFrame.from_dict(comptadors_equips, orient='index')
  print("\n INFORME DE RESULTATS LLIGA CATALANA")
  print("\n- Equip més golejador: ", df_est['gols_favor'].idxmax())
  print("\n- Equip més golejat: ", df_est['gols_contra'].idxmax())
  print("\n- Equips de la lliga i gols marcats per cadascun :")
  display(df_est[['gols_favor']].sort_values(by='gols_favor', ascending=False))
  print("\n- Classificació final :")
  # Asignamos nombre al índice para que muestre la palabra Equip como en el ejemplo
  df_est.index.name = 'equip'
  display(df_est.sort_values(by='punts', ascending=False))
# test
generar_informe_final(comptadors_equips)

 INFORME DE RESULTATS LLIGA CATALANA

- Equip més golejador:  Figueres

- Equip més golejat:  Vilafranca

- Equips de la lliga i gols marcats per cadascun :

                     gols_favor
Figueres                    161
Llagostera                  159
Vilafranca                  157
Terrassa                    147
Cornellà                    147
Sabadell                    141
Girona FC                   139
Badalona                    134
Olot                        132
RCD Espanyol                131
Nàstic de Tarragona         130
Lleida Esportiu             129
FC Barcelona                125
Sant Andreu                 123
Granollers                  122
Reus Deportiu               119
Cerdanyola                  117
Manlleu                     106
Prat                        106
Europa                       93

- Classificació final :

,gols_favor,gols_contra,guanyats,empatats,perduts,punts
equip,,,,,,
Girona FC,139,94,31,3,13,96
Llagostera,159,142,29,7,20,94
Sabadell,141,121,26,7,15,85
Cornellà,147,146,25,7,22,82
RCD Espanyol,131,144,23,11,21,80
Figueres,161,154,23,10,23,79
Lleida Esportiu,129,133,23,6,23,75
Terrassa,147,164,20,14,23,74
FC Barcelona,125,115,22,7,15,73
Vilafranca,157,172,20,12,25,72
Badalona,134,124,18,14,16,68
Nàstic de Tarragona,130,148,20,8,27,68
Reus Deportiu,119,111,20,8,16,68
Granollers,122,117,21,4,24,67
Olot,132,144,18,10,26,64
Sant Andreu,123,134,17,11,25,62
Manlleu,106,118,16,9,18,57
Cerdanyola,117,133,17,5,28,56
Prat,106,111,16,8,21,56
Europa,93,93,12,5,16,41

### Función :  main_classificacio_lliga  
Args :  (Opcional) String. Ruta a fichero txt o csv  
Acción :  llama a las funciones de lectura, cálculo de estadísticas e informe final    
Retorno :  None

In [ ]:
def main_classificacio_lliga(docu = None):
  if docu is None:
    docu = '/content/drive/MyDrive/CURS ESP DATA/S7Data/historic partits.txt'
  partits = llegir_i_netejar_dades(docu)
  if partits is not None:
    comptadors_equips = calcular_estadistiques(partits)
    generar_informe_final(comptadors_equips)

# test
main_classificacio_lliga()

 INFORME DE RESULTATS LLIGA CATALANA

- Equip més golejador:  Figueres

- Equip més golejat:  Vilafranca

- Equips de la lliga i gols marcats per cadascun :

                     gols_favor
Figueres                    161
Llagostera                  159
Vilafranca                  157
Terrassa                    147
Cornellà                    147
Sabadell                    141
Girona FC                   139
Badalona                    134
Olot                        132
RCD Espanyol                131
Nàstic de Tarragona         130
Lleida Esportiu             129
FC Barcelona                125
Sant Andreu                 123
Granollers                  122
Reus Deportiu               119
Cerdanyola                  117
Manlleu                     106
Prat                        106
Europa                       93

- Classificació final :

,gols_favor,gols_contra,guanyats,empatats,perduts,punts
equip,,,,,,
Girona FC,139,94,31,3,13,96
Llagostera,159,142,29,7,20,94
Sabadell,141,121,26,7,15,85
Cornellà,147,146,25,7,22,82
RCD Espanyol,131,144,23,11,21,80
Figueres,161,154,23,10,23,79
Lleida Esportiu,129,133,23,6,23,75
Terrassa,147,164,20,14,23,74
FC Barcelona,125,115,22,7,15,73
Vilafranca,157,172,20,12,25,72
Badalona,134,124,18,14,16,68
Nàstic de Tarragona,130,148,20,8,27,68
Reus Deportiu,119,111,20,8,16,68
Granollers,122,117,21,4,24,67
Olot,132,144,18,10,26,64
Sant Andreu,123,134,17,11,25,62
Manlleu,106,118,16,9,18,57
Cerdanyola,117,133,17,5,28,56
Prat,106,111,16,8,21,56
Europa,93,93,12,5,16,41